apiVersion: v1
kind: BuildConfig
metadata:
  name: ${project.artifactId}
spec:
  strategy:
    type: Source
    sourceStrategy:
      env:
        - name: MAVEN_ARGS
          value: "-Dbackend.url=http://localhost:8080/rest/catalogs/"