apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  to:
    kind: Service
    name: ${project.artifactId}