apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: "cdfront"
spec:
  template:
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "MAVEN_ARGS"
          value: "-Dbackend.url=http://localhost:8080/rest/catalogs/"
        name: "wildfly-swarm"
  triggers:
  - type: "ConfigChange"